### ISSUE TITLE
Parkinson's assesment task

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/carp-studies-app#158]
Few issues I see

- The back button is white with no contrast. I don't know if this is an app or a RP issue? @bardram 
- The swiping exercise did not work for me, at all. It seems to be reversed maybe? And it seems to be cumulative, as if I go back and do the exercise again, then it adds it to the previous result. I got 4 in the first and went back and did it again with ~4 correct I now got 8. I can even go past 10 if I continue this. Actually even if I submit the results and do an identical task again? @bardram

**Comment by bardram** [comment]
Fixed in Cognition Package release 1.5.3
