### ISSUE TITLE
When the button gets enabled the text disappears

### ISSUE THREAD

**Issue by urganerea** [cph-cachet/carp-studies-app#183]
![IMG_9052](https://github.com/cph-cachet/carp-studies-app/assets/104897317/5cba9b6c-9a20-48f3-85ae-043792360eaf)
![IMG_9053](https://github.com/cph-cachet/carp-studies-app/assets/104897317/cad8de39-1cfb-4aef-9a2c-357d8a0158c7)

**Comment by bardram** [comment]
https://carp.cachet.dk/research-package-api/

**Comment by bardram** [comment]
https://github.com/cph-cachet/carp-studies-app/blob/81560fa19e9c6798e4c773963f05c3934bae531e/lib/ui/carp_study_style.dart#L12
