### ISSUE TITLE
Login button even though already logged in

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-studies-app#184]
When I open the app the first time, I'm going through the login process. 

But then when I subsequently open the app, it still shows the login button and I have to press this

![IMG_5539](https://github.com/cph-cachet/carp-studies-app/assets/1196642/c2ca23f4-72c0-491e-9e29-19d448555cf6)

before being logged in on Computerome.

This is wrong - and not how the app used to work before the new Auth setup. 

You should go directly to the app, i.e. the home page (just like any other standard app).

**Comment by LarsRefsgaard** [comment]
Fixing PR waiting approval from @Panosfunk

**Comment by LarsRefsgaard** [comment]
Closed with #180
