### ISSUE TITLE
Can't connect to online services

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-studies-app#186]
The online services seem to not be connected - see below. When I click the "connect" label, nothing happens - they are still not connected.

![IMG_5540](https://github.com/cph-cachet/carp-studies-app/assets/1196642/407be60b-a63b-4ee4-a89a-64a9e5c1b2c2)

**Comment by LarsRefsgaard** [comment]
In progress

**Comment by bardram** [comment]
Fixed in branch `bardram/devices-services-upgrade`.
