### ISSUE TITLE
The app is consuming a lot of battery (on iOS)

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-studies-app#201]
When running the app, it consumes a lot of battery - by far the top on the "battery high score" in iOS. This is for the CATCH protocol.

It seems like it is sampling GPS data on a very high frequency.

This is a cross-cutting issue across:

* the app
* CAMS
* the CATCH protocol

![2023-12-18 23 45 58](https://github.com/cph-cachet/carp-studies-app/assets/1196642/65f63981-7189-4ba0-8af7-091070932651)

**Comment by LarsRefsgaard** [comment]
@cammdu
