### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by cammdu** [cph-cachet/carp-studies-app#202]
App version : 426
Platform : iOS API level ??

1. Initially, log in functions smoothly, and even the issue of logging in every time you reopen the app is fixed
2. now: for some reason, this doesn't work anymore and I can't log into the app except when I open it through TestFlight, this means that I can't do anything through the actual app icon.

**Comment by LarsRefsgaard** [comment]
@Panosfunk 
For the login part you can try and `await` the push of invitations on the login page, maybe?

About the data tab, take a look at #199 where I used this video to fix the error by putting the future in the BLoC, but it did not work as expected. https://www.youtube.com/watch?v=sqE-J8YJnpg
